### ISSUE TITLE
less version 3.0.2 is not currently supported

### ISSUE THREAD

**Issue by galvakojis** [highcharts/highcharts-editor#171]
Strange less error

```
npm info ok 
/bower_components/highcharts-editor/node_modules/accord/lib/index.js:34
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 3.0.2 is not currently supported
    at Object.exports.load (/bower_components/highcharts-editor/node_modules/accord/lib/index.js:34:13)
    at Object.<anonymous> (/bower_components/highcharts-editor/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/bower_components/highcharts-editor/gulpfile.js:13:12)
    at Module._compile (module.js:413:34)

```

**Comment by victorhgoli** [comment]
You have to follow the README.md

I had the same problem downloading de zip version and trying to install npm.

the solution is download directly from git repository: 
git clone https://github.com/highcharts/highcharts-editor
